# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_location', models.CharField(max_length=100)),
                ('event_cost', models.IntegerField()),
                ('event_time', models.DateField()),
            ],
        ),
    ]
